server:
  port: 8080

spring:
    profiles:
        active: test
    jpa:
        show-sql: true
        generate-ddl: true
        use-sql-comments: true
        ddl-auto: update

## 打印sql
logging:
  level:
    root: INFO
#    com.bumt.sensormgm.*: DEBUG

